export enum ErrorCode {
    VALIDATION_ERROR = "VALIDATION_ERROR",
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD",
    INVALID_FORMAT = "INVALID_FORMAT",
  
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
  
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
    POST_NOT_FOUND = "POST_NOT_FOUND",
    USER_NOT_FOUND = "USER_NOT_FOUND",
  
    DUPLICATE_ENTRY = "DUPLICATE_ENTRY",
    CONFLICT = "CONFLICT",
  
    PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE",
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
    DATABASE_ERROR = "DATABASE_ERROR",
    TIMEOUT_ERROR = "TIMEOUT_ERROR"
  }
  